Propaganda\Domain\Entity\Article:
  type: entity
  table: articles
  id:
    id:
      type: uuid
      generator: { strategy: NONE }
  fields:
    title:
      type: string
      length: 120
    coverImageId:
      type: uuid
      nullable: true
    content:
      type: contentType
    createdAt:
      type: datetime_immutable