Propaganda\Domain\Entity\Chart:
  type: entity
  table: charts
  id:
    id:
      type: uuid
      generator: { strategy: NONE }
  fields:
    name:
      type: text
    data:
      type: array
    columns:
      type: columnsType
    type:
      type: string
    createdAt:
      type: datetime_immutable
