Propaganda\Domain\Entity\Image:
  type: entity
  table: images
  id:
    id:
      type: uuid
      generator: { strategy: NONE }
  fields:
    description:
      type: text
    createdAt:
      type: datetime_immutable
      nullable: true
