# app/config/routing.yml
mocniak_propaganda:
  resource: '@MocniakPropagandaBundle/Resources/config/routing.yml'
  prefix: /propaganda/

homepage:
  path:     /
  defaults: { _controller: Propaganda\Infrastructure\Controller\DefaultController::indexAction }

show_article:
  path: /art/{slug}
  defaults: { _controller: Propaganda\Infrastructure\Controller\DefaultController::articleAction }

contact_page:
  path: /kontakt
  defaults: { _controller: Propaganda\Infrastructure\Controller\DefaultController::contactAction }

about_us_page:
  path: /o-nas
  defaults: { _controller: Propaganda\Infrastructure\Controller\DefaultController::aboutUsAction }

dashboard:
  path: /admin
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::dashboardAction }

create_article:
  path: /admin/create-article
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::createArticleAction }

get_article_data:
#  methods: [GET]
  path: /api/get-article-data/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::getArticleDataAction }

submit_edit_article:
  methods: [POST|OPTIONS]
  path: /api/submit-edit-article/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::submitEditArticleAction }

edit_article:
  methods: [GET]
  path: /admin/edit-article/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::editArticlePageAction }

publish_article:
  methods: [GET]
  path: /admin/publish-article/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::publishArticleAction }

withdraw_article:
  methods: [GET]
  path: /admin/withdraw-article/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::withdrawArticleAction }

create_image:
  path: /admin/create-image
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::createImageAction }

create_video:
  path: /admin/create-video
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::createVideoAction }

edit_video:
  path: /admin/edit-video/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::editVideoAction }

create_chart:
  path: /admin/create-chart
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::createChartAction }

edit_chart:
  path: /admin/edit-chart/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::editChartAction }

image_content:
  path: /image/image-content/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\DefaultController::ImageContentAction }

create_event:
  path: /admin/create-event
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::createEventAction }

edit_event:
  path: /admin/edit-event/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::editEventAction }

edit_featured_articles:
  path: /admin/edit-featured-articles
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::editFeaturedArticlesAction }
