homepage:
  path:     /
  defaults: { _controller: Propaganda\Infrastructure\Controller\DefaultController::indexAction }

show_article:
  path: /article/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\DefaultController::articleAction }

create_article:
  path: /admin/create-article
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::createArticleAction }

get_article_data:
#  methods: [GET]
  path: /admin/get-article-data/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::getArticleDataAction }

submit_edit_article:
  methods: [POST|OPTIONS]
  path: /admin/submit-edit-article/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::submitEditArticleAction }

edit_article:
  methods: [GET]
  path: /admin/edit-article/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::editArticlePageAction }

create_image:
  path: /admin/create-image
  defaults: { _controller: Propaganda\Infrastructure\Controller\AdminController::createImageAction }

image_content:
  path: /admin/image-content/{id}
  defaults: { _controller: Propaganda\Infrastructure\Controller\DefaultController::ImageContentAction }