# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
#            memory:
#                users:
#                    admin:
#                        password: $2y$12$YSfQG9JuB.FJsuScLtfNq.ctAKMIXnVEx0naZmGGlGvkdmVPUZhOK
#                        roles: 'ROLE_ADMIN'
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
#            anonymous: true
#            http_basic: true
#            # form_login: true
            anonymous: ~
#
#    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        # - { path: ^/profile, roles: ROLE_USER }
#    encoders:
#        Symfony\Component\Security\Core\User\User:
#            algorithm: bcrypt
#            cost: 12
